version: '3.8'
services:
  api-tests-dev:
    build: .
    image: api-tests
    container_name: api-test-dev
    volumes:
      - $PWD/test-reports/dev:/api-test-automation/mochawesome-report/
    network_mode: host
    command: run BOOKS BOOKS_DEV
  api-tests-stg:
    build: .
    image: api-tests
    container_name: api-test-stg
    volumes:
      - $PWD/test-reports/stg:/api-test-automation/mochawesome-report/
    network_mode: host
    command: run BOOKS BOOKS_STG
  api-tests-prd:
    build: .
    image: api-tests
    container_name: api-test-prd
    volumes:
      - $PWD/test-reports/prd:/api-test-automation/mochawesome-report/
    network_mode: host
    command: run BOOKS BOOKS_PRD


# docker run -v $PWD/test-reports:/api-test-automation/mochawesome-report/ --network=host --rm api-tests run BOOKS BOOKS_DEV